console.log("PARTE 1: Conceptos Fundamentales de Arrays");
console.log("PARTE 1.1");  
var datosUsuario = ["Sergio", 22, true];
console.log("Array completa creada de 0 = " + datosUsuario);
console.log("PARTE 1.2");  
console.log("Elemento de la posición 2 del array = " + datosUsuario[1]);
console.log("PARTE 1.3");  
console.log("Número de elementos que contiene el array " + datosUsuario.length);


console.log("PARTE 2: Modificación de Arrays: Añadir y Eliminar Elementos"); 
console.log("PARTE 2.1");  
datosUsuario.push("nuevo", 33);
console.log("Array después del push = " + datosUsuario);
console.log("PARTE 2.2");  
console.log("Elemento eliminado del array con pop es = " + datosUsuario.pop());
console.log("La array a quedado así = " + datosUsuario);
console.log("PARTE 2.3");  
datosUsuario.unshift(false);
console.log("Array después de hacer unshift = " + datosUsuario);
console.log("La nueva longitud es de = " + datosUsuario.length);
console.log("PARTE 2.4");  
console.log("Elemento eliminado del principio con shift es = " + datosUsuario.shift());
console.log("La array a quedado así = " + datosUsuario);

console.log("PARTE 3: Métodos Avanzados de Arrays");
console.log("PARTE 3.1");  
var arrayextra = ["Angel", 24, true];
var arrayTotal = datosUsuario.concat(arrayextra);
console.log("ArrayTotal, básicamente la concatenación el elemento .concat(la array que le añadimos a la primera) = " + arrayTotal);
console.log("PARTE 3.2");  
var arrayNumeros = [10, 40, 25, 79, 26, 32];
console.log("La array de numeros inicial = " + arrayNumeros);
console.log("La array con el sort de js = " + arrayNumeros.sort());
console.log("Sort ordena todos los valores como Strings, al 2 ser mayor que 1 pues pone 1 de primeras, y así sucesivamente comparando los numeros");
console.log("PARTE 3.3");  
console.log("Para que la ordenación sea numérica habría que utilizar una función de compare: ");
console.log("Ascendente: " + arrayNumeros.sort(function(a, b){return a - b}));
console.log("Lo que hace la función es coger 2 numeros del array y los resta, si el resultado es negativo el número en posición a se coloca antes que el b. Si el número es positivo el elemento b se coloca antes que a. Y si el resultado es 0 se mantiene a antes que b. Y así sucesivamente.");
console.log("Descendente: " + arrayNumeros.sort(function(a, b){return b - a}));
console.log("Lo que hace la función es coger 2 numeros del array y los resta, si el resultado es negativo el número en posición b se coloca antes que el a. Si el número es positivo el elemento a se coloca antes que b. Y si el resultado es 0 se mantiene a antes que b. Y así sucesivamente.");
console.log("PARTE 3.4");  
console.log("arrayTotal antes de hacer nada = " + arrayTotal);
let borrado = arrayTotal.splice(2, 2, "Hola", 78);
console.log("arrayTotal después del splice = " + arrayTotal);
console.log("Elementos eliminados de arrayTotal = " + borrado);
console.log("Lo que hace splice es elegir la posición donde se empieza a modificar el array, el número de elementos que se eliminan y se dan los elementos que sustituyen a los eliminados");

console.log("PARTE 4: Funciones Predefinidas de validación y conversión");
console.log("PARTE 4.1");  
var cadena = "esto es una cadena";
console.log(cadena);
console.log("Resultado del isNan() = " + isNaN(cadena));
console.log("PARTE 4.2");  
console.log("Al intentar hacer parseInt a la primera cadena" + parseInt(cadena));
var cadena2 = "5,4";
console.log(cadena2);
console.log("Nueva cadena 5,4 para parsear a INT = " + parseInt(cadena2));
console.log("Llevamos esta misma cadena de vuelta a Float (no le añade la ,) = " + parseFloat(cadena2));
console.log("PARTE 4.3");  
var cadena3 = "Hola";
console.log(cadena3);
console.log("Usamos number para pasar de caracter a numero = " + Number(cadena3));
console.log("Usamos string para pasar de numero a caracter = " + String(cadena2)); 